# Generated by Django 5.0.4 on 2024-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Years_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Headline1', models.CharField(blank=True, max_length=100, null=True)),
                ('about1', models.TextField(blank=True, null=True)),
                ('Years_2', models.CharField(blank=True, max_length=100, null=True)),
                ('Headline2', models.CharField(blank=True, max_length=100, null=True)),
                ('about2', models.TextField(blank=True, null=True)),
                ('Years_3', models.CharField(blank=True, max_length=100, null=True)),
                ('Headline3', models.CharField(blank=True, max_length=100, null=True)),
                ('about3', models.TextField(blank=True, null=True)),
                ('Years_4', models.CharField(blank=True, max_length=100, null=True)),
                ('Headline4', models.CharField(blank=True, max_length=100, null=True)),
                ('about4', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmazingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=100, null=True)),
                ('role1', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Team/')),
                ('twitter1', models.URLField(blank=True, max_length=150, null=True)),
                ('facebook1', models.URLField(blank=True, max_length=150, null=True)),
                ('linkeldin', models.URLField(blank=True, max_length=150, null=True)),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
                ('role2', models.CharField(blank=True, max_length=100, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Team/')),
                ('twitter2', models.URLField(blank=True, max_length=150, null=True)),
                ('facebook2', models.URLField(blank=True, max_length=150, null=True)),
                ('linkeldin2', models.URLField(blank=True, max_length=150, null=True)),
                ('name3', models.CharField(blank=True, max_length=100, null=True)),
                ('role3', models.CharField(blank=True, max_length=100, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Team/')),
                ('twitter3', models.URLField(blank=True, max_length=150, null=True)),
                ('facebook3', models.URLField(blank=True, max_length=150, null=True)),
                ('linkeldin3', models.URLField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liquidation_Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_1', models.CharField(blank=True, max_length=100, null=True)),
                ('image_step_1', models.ImageField(blank=True, null=True, upload_to='liquidation/')),
                ('desc_step_1', models.CharField(blank=True, max_length=400, null=True)),
                ('step_2', models.CharField(blank=True, max_length=100, null=True)),
                ('image_step_2', models.ImageField(blank=True, null=True, upload_to='liquidation/')),
                ('desc_step_2', models.CharField(blank=True, max_length=400, null=True)),
                ('step_3', models.CharField(blank=True, max_length=100, null=True)),
                ('image_step_3', models.ImageField(blank=True, null=True, upload_to='liquidation/')),
                ('desc_step_3', models.CharField(blank=True, max_length=400, null=True)),
                ('step_4', models.CharField(blank=True, max_length=100, null=True)),
                ('image_step_4', models.ImageField(blank=True, null=True, upload_to='liquidation/')),
                ('desc_step_4', models.CharField(blank=True, max_length=400, null=True)),
                ('step_5', models.CharField(blank=True, max_length=100, null=True)),
                ('image_step_5', models.ImageField(blank=True, null=True, upload_to='liquidation/')),
                ('desc_step_5', models.CharField(blank=True, max_length=400, null=True)),
                ('step_6', models.CharField(blank=True, max_length=100, null=True)),
                ('image_step_6', models.ImageField(blank=True, null=True, upload_to='liquidation/')),
                ('desc_step_6', models.CharField(blank=True, max_length=400, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurSocials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=150, null=True)),
                ('twitter', models.URLField(blank=True, max_length=150, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('service_description_1', models.CharField(blank=True, max_length=250, null=True)),
                ('service_name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('service_description_2', models.CharField(blank=True, max_length=250, null=True)),
                ('service_name_3', models.CharField(blank=True, max_length=100, null=True)),
                ('service_description_3', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
