# Generated by Django 5.0.4 on 2024-04-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLiquidity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidation_steps',
            name='desc_step_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidation_steps',
            name='desc_step_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidation_steps',
            name='desc_step_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidation_steps',
            name='desc_step_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidation_steps',
            name='desc_step_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidation_steps',
            name='desc_step_6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
