# Generated by Django 5.0.4 on 2024-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLiquidity', '0002_alter_liquidation_steps_desc_step_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_description_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
