# Generated by Django 5.0.4 on 2024-05-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLiquidity', '0003_alter_services_service_description_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailrush', models.URLField(blank=True, null=True)),
                ('merchant', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
