# Generated by Django 5.0.4 on 2024-05-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLiquidity', '0004_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
